#pragma config(Motor,  port10,           RightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           ClawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port1,          LeftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void tankdrive()
{
	motor[LeftMotor]=vexRT[Ch2]*0.75;
	motor[RightMotor]=vexRT[Ch3]*0.75;
}

void armcontrol()
{
	motor[ArmMotor]=vexRT[Ch3Xmtr2]*0.75;
	motor[ClawMotor]=vexRT[Ch1Xmtr2]*0.75;
}

task main()
{
	while(vexRT[Btn7U] == 0)
		//wait in this loop until button 7U is pushed
	{
	}
	clearTimer(T1);
	// Clear timer 1 and let it start counting
	while(time1[T1]<15000)
		// AUTONOMOUS PORTION
	{
	motor[RightMotor]=-80;//left
	motor[LeftMotor]=80;
	wait1Msec(150);
	motor[ArmMotor]=80;
	wait1Msec(500);
	motor[RightMotor]=60;
	motor[LeftMotor]=90;
	wait1Msec(200);
	motor[ClawMotor]=80;
	wait1Msec(500);
	wait1Msec(250);
	motor[ArmMotor]=-80;
	wait1Msec(500);
	motor[LeftMotor]=-80;
	motor[RightMotor]=-80;
	wait1Msec(1000);
	break;
	}

	motor[LeftMotor] = 0;
	motor[RightMotor] = 0;
	motor[ArmMotor] = 0;
	motor[ClawMotor] = 0;
	wait1Msec(1000);

	clearTimer(T1);
	while(time1[T1]<105000)
	{
		tankdrive();
		armcontrol();
}}
